export default {
  nav: [
    { label: 'Features', href: '/features/' },
    { label: 'Add-ons', href: '/addons/' },
    { label: 'Guides', href: '/guides/' },
    { label: 'Workflows', href: '/workflows/' },
  ],
  install: { label: 'Install', href: '/#get-started' },
  home: 'Home',
  onThisPage: 'On this page',
  forLabel: 'For:',
  feature: {
    eyebrow: 'Nepal Compliance / Feature guide',
    sideTitle: 'Features',
    sideNote: 'Requires ERPNext and Frappe HR.',
    sideNoteLink: 'Installation requirements',
    questions: 'Questions about this feature',
    references: 'Technical references',
    referencesNote: 'For your implementation team.',
    next: { title: 'Does it fit your business?', body: 'See where to start.', label: 'Find your starting point', href: '/workflows/' },
    related: 'Related features',
  },
  addon: {
    eyebrowSuffix: 'Add-on guide',
    sideTitle: 'Add-on integrations',
    sideNote: 'Looking for the app’s included capabilities?',
    sideNoteLink: 'Browse core features',
    questions: 'Questions and answers',
    references: 'References and scope',
    referencesNote: 'Reviewed September 2026.',
    next: {
      title: 'Discuss your integration requirements',
      body: 'Share the workflow, your ERPNext version, and the provider or device. Never post credentials or employee data.',
      label: 'Open project discussions',
      href: 'https://github.com/yarsa/nepal-compliance/discussions',
    },
    related: 'Related integrations',
  },
  guide: {
    eyebrowSuffix: 'Practical guide',
    sideTitle: 'In this guide',
    byline: 'Published by ERP Nepal',
    editorial: 'Editorial approach',
    references: 'References:',
    questions: 'Questions and answers',
    sources: 'Sources and further reading',
    sourcesNote: 'Checked 28 September 2026.',
    related: 'Related guides',
    projectPages: 'Related project pages',
    tableSuffix: 'comparison',
  },
  breadcrumbs: { features: 'Features', addons: 'Add-ons', guides: 'Guides' },
  search: {
    label: 'Search',
    placeholder: 'Search guides, features and add-ons…',
    empty: 'No matches. Try a shorter word.',
    hint: 'Enter to open · Esc to close',
    groups: { pages: 'Pages', features: 'Features', guides: 'Guides', addons: 'Add-ons' },
  },
  a11y: {
    skip: 'Skip to content',
    main: 'Main',
    menu: 'Menu',
    theme: 'Toggle dark mode',
    light: 'Light',
    dark: 'Dark',
    language: 'Language',
    github: 'Nepal Compliance on GitHub',
    stars: 'stars',
    site: 'Site',
    project: 'Project',
  },
}
