import { shell } from './guide-pages.mjs';
const e = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const crumbs = label => `<nav class="breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="../">Home</a></li><li aria-current="page">${label}</li></ol></nav>`;
const workflows = { 'accounting-and-vat':'accounting', invoicing:'billing', cbms:'billing', payroll:'people', 'hr-and-leave':'people', 'audit-and-reports':'accounting billing', 'nepali-dates':'accounting billing people' };
export function renderFeatureIndex(features) {
 return shell('Features for accounting, billing, and payroll in Nepal', 'Explore Nepal Compliance features for everyday business: VAT registers, invoice controls, payroll contributions, leave, audit records, and local dates.', '../', `${crumbs('Features')}<header class="guide-index-header"><p class="section-label">Features</p><h1>Keep billing, accounts, and payroll in order</h1><p class="feature-lead">Give your team the local tools to issue invoices, review VAT records, prepare salaries, and manage employee leave.</p><p>Nepal Compliance works with ERPNext and Frappe HR. Explore each workflow to see how it fits your business.</p><a class="text-link" href="../for-your-business/">See if it fits your business →</a></header>
<div class="workflow-explorer" hidden><h2 id="workflow-label">Explore your team's work</h2><div class="workflow-buttons" role="group" aria-labelledby="workflow-label"><button type="button" data-workflow="all" aria-pressed="true">All features</button><button type="button" data-workflow="accounting" aria-pressed="false">Accounting</button><button type="button" data-workflow="billing" aria-pressed="false">Billing</button><button type="button" data-workflow="people" aria-pressed="false">Payroll &amp; HR</button></div><p id="workflow-description">Explore everyday business workflows.</p><p id="workflow-status" role="status" aria-live="polite" aria-atomic="true">7 features</p></div>
<div class="feature-directory">${features.map((f,i)=>`<article data-workflows="${workflows[f.slug]}"><span class="feature-number">0${i+1}</span><div><h2><a href="./${e(f.slug)}/">${e(f.title)}</a></h2><p>${e(f.description)}</p><a class="text-link" href="./${e(f.slug)}/">See how it works →</a></div></article>`).join('')}</div>
<section class="feature-next"><h2>More HR tools are coming</h2><p>Nepal HRMS is in beta testing before its expanded employee app, attendance, and payroll capabilities are brought into Nepal Compliance.</p><a href="../nepal-hrms/">Preview Nepal HRMS →</a></section>`, 'Nepal Compliance');
}
export function renderAddonIndex(addons) {
 return shell('Add-ons for payments, attendance, and business services', 'Explore Nepal Compliance integration options for QR payments, CORPORATEPAY, SMS, attendance devices, ecommerce, and local business services.', '../', `${crumbs('Add-ons')}<header class="guide-index-header"><p class="section-label">Add-on integrations</p><h1>Connect the services your business already uses</h1><p class="feature-lead">Bring payments, attendance devices, messaging, and online orders into your business workflows.</p><p>These are optional integrations. Provider access, device compatibility, implementation scope, and fees are agreed separately from the core app.</p></header><div class="addon-directory">${addons.map(a=>`<article><p class="section-label">${e(a.category)}</p><h2><a href="./${e(a.slug)}/">${e(a.shortTitle)}</a></h2><p>${e(a.description)}</p><a class="text-link" href="./${e(a.slug)}/">Explore this integration →</a></article>`).join('')}</div><section class="feature-next"><h2>Start with the workflow you want to improve</h2><p>Choose the service you use, check the requirements, and agree what should happen when a payment, order, or attendance record arrives.</p><a href="../guides/">Read practical guides →</a></section>`, 'Nepal Compliance');
}
export function renderBusinessPage() {
 return shell('Is Nepal Compliance right for your business?', 'See how Nepal Compliance can support a shop, trading business, service company, or growing team, and what to consider before choosing your setup.', '../', `${crumbs('For your business')}<header class="guide-index-header"><p class="section-label">For small and growing businesses</p><h1>Find the workflows that fit your business</h1><p class="feature-lead">Start with the work your team does every day: billing customers, reviewing accounts, and paying employees.</p><p>Nepal Compliance adds local accounting and HR capabilities to ERPNext and Frappe HR. These examples show where to begin; your setup depends on the records, approvals, and services you need.</p><a class="button" href="../features/">Explore all features →</a></header>
<div class="guide-directory"><article><p class="section-label">Shops and trading businesses</p><h2>Keep invoices and VAT records connected</h2><p>Use invoice controls and sales, purchase, and return registers to review daily billing and prepare records for your accountant. With ERPNext, these workflows sit alongside your stock and purchasing records.</p><a href="../features/invoicing/">Explore billing →</a></article><article><p class="section-label">Service businesses</p><h2>Review customer billing and corrections</h2><p>Keep invoice references, reprints, and cancellation history available when a customer asks about a bill. Use ERPNext's payment workflows to review what has been paid and what remains outstanding.</p><a href="../guides/qr-payment-reconciliation/">Understand payment reconciliation →</a></article><article><p class="section-label">Teams with employees</p><h2>Prepare payroll with clearer inputs</h2><p>Work with salary components, local contributions, employee records, and leave allocation. Agree your payroll policies and review sample salary slips before the first pay run.</p><a href="../features/payroll/">Explore payroll →</a></article></div>
<section class="feature-page-section guide-editorial"><h2>What you need to get started</h2><ul><li><strong>Your business records:</strong> customers, suppliers, opening balances, and employee details, as relevant.</li><li><strong>A working setup:</strong> ERPNext, Frappe HR, and Nepal Compliance, with hosting, backups, and maintenance arranged.</li><li><strong>A responsible team:</strong> someone to own the rollout, train staff, and review accounting and payroll configuration.</li></ul><p>There is no software license fee for Nepal Compliance. Hosting, implementation, training, and ongoing support are separate costs. If you only need occasional invoices and have no one to maintain an ERP, compare the operating effort before committing.</p></section>
<section class="feature-next"><h2>Try your own business example</h2><p>Ask your implementer to walk through a sale, a partial payment, a return, and a salary slip using sample records. Check that your team can understand the results.</p><a class="button" href="../guides/choosing-erp-software-nepal/">Use the business evaluation checklist →</a></section>`, 'Nepal Compliance');
}
