const e = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
function shell(title, description, prefix, body) {
  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#ffffff"><meta name="referrer" content="strict-origin-when-cross-origin">
<title>${e(title)} | ERP Nepal Guides</title><meta name="description" content="${e(description)}">
<meta property="og:type" content="website"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta name="twitter:card" content="summary">
<link rel="icon" type="image/png" sizes="96x96" href="${prefix}assets/favicon.png"><link rel="icon" type="image/svg+xml" sizes="any" href="${prefix}assets/favicon.svg">
<link rel="stylesheet" href="${prefix}styles.css"><script src="${prefix}app.js" defer></script>
</head><body><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><div class="container nav-wrap"><a class="brand" href="${prefix}" aria-label="Nepal Compliance home"><img src="${prefix}assets/nepal-compliance.svg" width="35" height="35" alt=""><span>Nepal Compliance</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation" hidden>Menu <span aria-hidden="true">≡</span></button><nav id="navigation" aria-label="Main navigation"><a href="${prefix}#features">Features</a><a href="${prefix}#addons">Add-ons</a><a href="${prefix}nepal-hrms/">Nepal HRMS</a><a href="${prefix}guides/">Guides</a><a href="${prefix}#get-started">Installation</a></nav></div></header>
<main id="main" class="container feature-page">${body}</main>
<footer class="site-footer"><div class="container"><div class="footer-top"><a class="brand" href="${prefix}">Nepal Compliance</a><nav aria-label="Project resources"><a href="${prefix}guides/">All guides</a><a href="${prefix}guides/#editorial">Editorial approach</a><a href="${prefix}sitemap.xml">Sitemap</a></nav></div><div class="footer-bottom"><p>Published by ERP Nepal. Practical guidance with linked sources.</p><a href="https://github.com/yarsa/erpnepal.org/issues">Suggest a correction</a></div></div></footer>
</body></html>`;
}
export function renderGuideIndex(guides) {
  return shell('Practical ERP, accounting, and payroll guides for Nepal', 'Answers to practical questions about ERP software, VAT invoices, CBMS, payroll, payment reconciliation, attendance, migration, and backups in Nepal.', '../', `
<nav class="breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="../">Home</a></li><li aria-current="page">Guides</li></ol></nav>
<header class="guide-index-header"><p class="section-label">ERP Nepal / Practical guides</p><h1>Working with ERP software in Nepal</h1><p class="feature-lead">Make software decisions, prepare your records, and check the workflows that matter to your business.</p><p>These guides answer specific setup and operating questions. Each includes practical examples or checks and links to the documentation behind the explanation.</p></header>
<div class="guide-directory">${guides.map(g=>`<article><p class="section-label">${e(g.category)}</p><h2><a href="./${e(g.slug)}/">${e(g.title)}</a></h2><p>${e(g.description)}</p><a class="text-link" href="./${e(g.slug)}/" aria-label="Read ${e(g.title)}">Read guide <span aria-hidden="true">→</span></a></article>`).join('')}</div>
<section class="feature-page-section guide-editorial" id="editorial"><h2>How these guides are prepared</h2><p>Published by ERP Nepal. Topics are selected from recurring public questions and relevant search results, then checked against official product documentation, provider information, or government material. We do not claim measured keyword volumes or a ranking of the most searched topics.</p><p>Our checklists, sample records, and scenarios are illustrative implementation advice. Source links identify the supporting documentation; they do not imply endorsement. Software versions and provider arrangements can change. Tax and payroll articles explain setup and verification tasks, and do not replace a current determination from your accountant or the relevant authority.</p><p>These guides were prepared with AI assistance and checked against the linked sources. No independent accounting, legal, or regulatory sign-off is claimed. Sources were checked on <time datetime="2026-09-28">28 September 2026</time>. Corrections are welcome through the <a href="https://github.com/yarsa/erpnepal.org/issues">website issue tracker</a>; please omit employee records, account credentials, and private business documents.</p></section>`);
}
export function renderGuidePage(guide, guides) {
  const sourceMap = new Map(guide.sources.map(s=>[s.id,s]));
  return shell(guide.title, guide.description, '../../', `
<nav class="breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="../../">Home</a></li><li><a href="../">Guides</a></li><li aria-current="page">${e(guide.title)}</li></ol></nav>
<div class="guide-layout"><aside class="feature-navigation"><nav aria-label="On this page"><p class="section-label">In this guide</p>${guide.sections.map((s,i)=>`<a href="#section-${i+1}">${e(s.heading)}</a>`).join('')}<a href="#questions">Questions and answers</a><a href="#sources">Sources</a></nav></aside>
<article class="feature-article"><header class="feature-page-header"><p class="section-label">${e(guide.category)} / Practical guide</p><h1>${e(guide.title)}</h1><p class="guide-byline">Published by ERP Nepal · <time datetime="2026-09-28">28 September 2026</time> · <a href="../#editorial">Editorial approach</a></p><p class="feature-lead">${e(guide.answer)}</p></header>
<details class="guide-mobile-contents"><summary>On this page</summary><nav aria-label="Article contents">${guide.sections.map((s,i)=>`<a href="#section-${i+1}">${e(s.heading)}</a>`).join('')}<a href="#questions">Questions and answers</a><a href="#sources">Sources</a></nav></details>
${guide.sections.map((section,i)=>`<section class="feature-page-section" id="section-${i+1}"><h2>${e(section.heading)}</h2>${section.paragraphs.map(p=>`<p>${e(p)}</p>`).join('')}${section.items?.length?`<ul>${section.items.map(p=>`<li>${e(p)}</li>`).join('')}</ul>`:''}${section.table?`<div class="guide-table" role="region" tabindex="0" aria-label="${e(section.heading)} comparison"><table><caption>${e(section.heading)}</caption><thead><tr>${section.table.headers.map(h=>`<th scope="col">${e(h)}</th>`).join('')}</tr></thead><tbody>${section.table.rows.map(r=>`<tr>${r.map((v,j)=>j===0?`<th scope="row">${e(v)}</th>`:`<td>${e(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:''}${section.sources?.length?`<p class="guide-citations">References: ${section.sources.map(id=>{const s=sourceMap.get(id);if(!s)throw new Error('Unknown source '+id+' in '+guide.slug);return `<a href="${e(s.url)}">${e(s.label)}</a>`;}).join(' · ')}</p>`:''}</section>`).join('')}
<section class="feature-page-section feature-questions" id="questions"><h2>Questions and answers</h2>${guide.questions.map(q=>`<section><h3>${e(q.question)}</h3><p>${e(q.answer)}</p></section>`).join('')}</section>
<section class="feature-page-section source-section" id="sources"><h2>Sources and further reading</h2><p>Sources checked 28 September 2026. Use the linked documentation for version-specific details and current requirements.</p><ul>${guide.sources.map(s=>`<li><a href="${e(s.url)}">${e(s.label)}</a></li>`).join('')}</ul></section>
<nav class="related-features" aria-label="Related guides"><h2>Related guides</h2>${guide.related.map(slug=>{const g=guides.find(x=>x.slug===slug);if(!g)throw new Error('Missing related guide '+slug);return `<a href="../${e(g.slug)}/">${e(g.title)} <span aria-hidden="true">→</span></a>`;}).join('')}</nav>
<nav class="related-features" aria-label="Related project pages"><h2>Related project pages</h2>${guide.featureLinks.map(link=>`<a href="../../${e(link.path)}">${e(link.label)} <span aria-hidden="true">→</span></a>`).join('')}</nav>
</article></div>`);
}
